# This is a configuration file for PyPIC3D
[simulation_parameters]
name = "Electron Positron Reconnection in Harris Current Sheet"
Nt   = 1500
x_bc = "periodic"
z_bc = "conducting"
solver = 'fdtd'
Nx = 500
Ny = 1
Nz = 500
x_wind = 0.0008
y_wind = 1
z_wind = 0.0008
verbose = false
electrostatic = false
cfl = 0.1
shape_factor = 2
relativistic = true

[plotting]
plotting_interval = 50
plot_vtk_particles = false
plot_phasespace = true

[field1]
name = "Bx field"
type = 3
path = "Bx.npy"

[field2]
name = "Bz field"
type = 5
path = "Bz.npy"

[particle1]
name = "peak electrons"
N_particles = 100000
charge = -1.602e-19
mass   = 9.1093837e-31
vth    = 14989622.9
weight = 21183911444.379375
initial_x = 'electron_x.npy'
initial_y = 'electron_y.npy'
initial_z = 'electron_z.npy'
initial_vx = 'electron_vx.npy'
initial_vy = 'electron_vy.npy'
initial_vz = 'electron_vz.npy'
x_bc = "periodic"
z_bc = "reflecting"
y_bc = "periodic"

[particle2]
name = "peak ions"
N_particles = 100000
charge = 1.602e-19
mass = 9.1093837e-31
vth  = 14989622.9
weight = 21183911444.379375
initial_x = 'ion_x.npy'
initial_y = 'ion_y.npy'
initial_z = 'ion_z.npy'
initial_vx = 'ion_vx.npy'
initial_vy = 'ion_vy.npy'
initial_vz = 'ion_vz.npy'
x_bc = "periodic"
z_bc = "reflecting"
y_bc = "periodic"

[particle3]
name = "background electrons"
N_particles = 30000
charge = -1.602e-19
mass   = 9.1093837e-31
vth    = 14989622.9
weight = 21183911444.379375
x_bc = "periodic"
z_bc = "reflecting"
y_bc = "periodic"

[particle4]
name = "background ions"
N_particles = 30000
charge = 1.602e-19
mass = 9.1093837e-31
vth  = 14989622.9
weight = 21183911444.379375
x_bc = "periodic"
z_bc = "reflecting"
y_bc = "periodic"
